% Screen
PIXEL_TIME = 1;
VGA_HORIZONTAL_BACK_PORCH = 220;
VGA_HORIZONTAL_FRONT_PORCH = 110;
VGA_HORIZONTAL_RESOLUTION = 1280;
VGA_HORIZONTAL_SYNC = 40;
VGA_VERTICAL_BACK_PORCH = 20;
VGA_VERTICAL_FRONT_PORCH = 5;
VGA_VERTICAL_RESOLUTION = 720;
VGA_VERTICAL_SYNC = 5;