% Screen
PIXEL_TIME = 1;
VGA_HORIZONTAL_BACK_PORCH = 1;
VGA_HORIZONTAL_FRONT_PORCH = 1;
VGA_HORIZONTAL_RESOLUTION = 300;
VGA_HORIZONTAL_SYNC = 1;
VGA_VERTICAL_BACK_PORCH = 1;
VGA_VERTICAL_FRONT_PORCH = 1;
VGA_VERTICAL_RESOLUTION = 300;
VGA_VERTICAL_SYNC = 1;

