vlib work
vcom  mandelbrot_top_pkg.vhd
vcom  enable_deglitch.vhd
vcom  down_deglitch.vhd
vcom  horizontal_accumulator.vhd
vcom  left_degltich.vhd
vcom  right_deglitch.vhd
vcom  up_deglitch.vhd
vcom  vertical_accumulator.vhd
vcom  zoom_accumulator.vhd
vcom  zoom_in_deglitch.vhd
vcom  zoom_out_deglitch.vhd
vcom  keyboard_handler.vhd
vcom  mandelbroot_array.vhd
vcom  mandelbroot_pipeline.vhd
vcom  plane_converter.vhd
vcom  horizontal_ranges.vhd
vcom  vertical_ranges.vhd
vcom  vga_driver.vhd
vcom  mandelbrot_core.vhd
vcom  video_test_deglitch.vhd
vcom  mandelbrot_top.vhd
